# Generated by Django 5.0 on 2024-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bestseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Márka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rendszerezes', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('cég', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200)),
                ('image_2', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
